packages:
  - 'packages/*'
  - 'examples/*'
  - 'homepage/*'
  - 'starters/*'
  - 'tests/*'
  - 'crates/cojson-core-wasm'

catalog:
  "@biomejs/biome": 2.1.3
  typescript: 5.6.2
  vite: 6.3.5
  vitest: 3.2.4
  "@vitest/browser": 3.2.4
  "@vitest/coverage-istanbul": 3.2.4
  "@vitest/coverage-v8": 3.2.4
  "@vitest/ui": 3.2.4
