name: Code quality

concurrency:
  # For pushes, this lets concurrent runs happen, so each push gets a result.
  # But for other events (e.g. PRs), we can cancel the previous runs.
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: 
      - "main"
  pull_request:


jobs:
  quality:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4
      - name: Run Biome
        run: biome ci .

      - name: Check Catalog Dependencies
        run: node scripts/check-catalog-deps.js
