name: Playwright Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    timeout-minutes: 60
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Install root dependencies
        run: pnpm install && pnpm exec turbo build --filter="./packages/*"

      - name: Install project dependencies
        run: pnpm install
        working-directory: ./homepage/homepage

      - name: Pnpm Build
        run: pnpm exec turbo build
        working-directory: ./homepage/homepage

      - name: Install Playwright Browsers
        run: pnpm exec playwright install
        working-directory: ./homepage/homepage

      - name: Run Playwright tests
        run: pnpm exec playwright test
        working-directory: ./homepage/homepage

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: homepage-playwright-report
          path: ./homepage/homepage/playwright-report/
          retention-days: 30
